### ISSUE TITLE
xml:lang

### ISSUE THREAD

**Issue by rossjones** [geo-data/python-skos#3]
In cases where the skos:prefLabel might look like 

```xml 
        <skos:prefLabel xml:lang="fr">Notion de test Unicode: ó</skos:prefLabel>
        <skos:prefLabel xml:lang="en">Unicode test concept: ó</skos:prefLabel>
        <skos:prefLabel xml:lang="es">Concepto de prueba Unicode: ó</skos:prefLabel>
```

it isn't clear what python-skos returns (i.e. it seems to vary).  Would you be open to a PR where lang is supplied to the loader and the specified language version returned in _loadConcepts for prefLabel and altLabel? This is currently blocking us shipping this for our ckan extension and running on data.gov.uk.

**Comment by homme** [comment]
Many thanks for the pull request.  If you need this published as a new python-skos version on the Python Package Index let me know.
